### PR TITLE
Issue Fixes

### PR DESCRIPTION
**Pull request by robweber**
There are multiple changes referenced here. Sorry for not doing separate PRs but once I got going on this I'd already done a bunch before realizing these might have usefulness as a PR. My original intent was just to play with this for fun myself. 

Some of these are in reference to Issues you have already created. __None of them change any core functionality__ and have been tested. While wrapping functions in a Class wasn't strictly necessary I wanted to organize some of the code a bit as I want to tackle threading for multiple directories next. 

Here is a summary of the changes so far: 

1. Added a requirements.txt file, I ran into a python error of missed deps the first time running this
2. updated the output logging to list when Intros/Outros are being detected and on what file. Previously this gave an index, but because of the sorting it was hard to tell what file. This makes the output way more readable (see below). 
3. Wrapped core functions in Detector class. This eliminated many of the redundant variable passing calls that were done between functions and opens the door for future improvements like threading. 
4. Added a debug mode (#17). Right now this is a flag __--debug__ that can be set. It will keep the image directories. Additional debug logging could be added in the future. 
5. Changed the directory path for the images to be local to the script (#13). This is just a simple "jpgs" directory with subs for each video was was done before. Will be removed or kept based on --debug flag. 

Example Output from new logging format: 

```

Threshold: 0.35
Method: all_match
Finding Intros
        Futurama/Futurama - Amazon Women in the Mood.S03.E05.avi
        Futurama/Futurama - The Luck of the Fryrish.S03.E10.avi
Finding Outros
        Futurama/Futurama - Amazon Women in the Mood.S03.E05.avi
        Futurama/Futurama - The Luck of the Fryrish.S03.E10.avi
Timing files created.

```

### CODE REVIEW

**Comment by Razzeee** [comment]
Thank you, I hope I can find some time in the next days to tackle this

**Comment by robweber** [comment]
I kept going in a different branch on my fork with the multithreading. All of these fixes are there but I had to make a lot of modifications in order to get directory traversal and threading to work properly. I also ended up removing all ```print()``` statements in favor of the ```logging``` module as it was more thread friendly. I also managed to fix the issue you found with #15 

Let me know if you'd prefer to scrap this and take a look at that version instead. I can do another PR detailing the changes. https://github.com/robweber/notrobro/tree/multithreading/

**Comment by Razzeee** [comment]
Yes, please submit that instead

**Comment by robweber** [comment]
closing due to #27

**Pull request closed without merging**
